name: Selenium Tests

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: Ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Print working directory
      run: pwd
    
    - name: List files
      run: ls -a 

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.9'

    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      with:
        path: 'requirements.txt'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Install Firefox
      uses: browser-actions/setup-firefox@v1

    - name: Run tests
      run: python -m main.py


 